### ISSUE TITLE
ZonalStatistics limited to 255 polygon

### ISSUE THREAD

**Issue by SebastienPeillet** [remicres/SimpleExtractionTools#1]
Hi Remi !

I tested ZonalStatistics application but it seems that it's limited to the first 255 polygons.

The [**size_t** ](https://github.com/remicres/SimpleExtractionTools/blob/d6727d9371757123b086687ba03fb899020c37c1/app/otbZonalStatistics.cxx#L51) type of _LabelValueType_ is problematic in line [234](https://github.com/remicres/SimpleExtractionTools/blob/d6727d9371757123b086687ba03fb899020c37c1/app/otbZonalStatistics.cxx#L234). When the value is higher than 255, fid equals 0 and statistics aren't compute.

I changed **size_t** with **unsigned int** and it works now !

**Comment by SebastienPeillet** [comment]
hum I just saw that it's an old version of ZonalStatistics compare of [gitlab repository](https://gitlab.irstea.fr/remi.cresson/SimpleExtractionTools/blob/enhancements/app/otbZonalStatistics.cxx) haha, my bad !

**Comment by remicres** [comment]
Hi @SebastienPeillet 
This is an old remote module... We are currently working on pushing this into OTB (see [here](https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/merge_requests/222))

This should be ready for the next release :wink:
